FROM quay.io/containerlisp/lisp-10-ubi8

RUN curl -L https://github.com/etcd-io/etcd/releases/download/v3.5.0/etcd-v3.5.0-linux-amd64.tar.gz | tar xvfz - && mkdir /opt/app-root/src/bin && mv etcd-v3.5.0-linux-amd64/* /opt/app-root/src/bin
RUN sbcl --eval '(dolist (p (list :alexandria :async-process :bordeaux-threads :cl-base64 :cl-json :cl-ppcre :cl-toml :drakma :flexi-streams :log4cl)) (ql:quickload p))'
